name: default
# channels:
#   - conda-forge
#   - defaults
dependencies:
  - python=3.10

  - jupyterlab
  - ipython
  - jupyter_console

  - numpy
  - scipy
  - pandas
  - numba

  - matplotlib
  - cartopy
  - cmocean
  - tabulate

  - xarray
  - dask
  - netCDF4
  - h5netcdf
  - h5py
  - bottleneck
  - cftime
  - pydap
  - nc-time-axis

  - boost-histogram
  - dask-histogram
  - xhistogram

  - graphviz
  - python-graphviz

  - motuclient
  - shapely

  - sphinx
  - sphinx_rtd_theme

  - bibtexparser

  - python-lsp-server
  - flake8
  - pycodestyle
  - pydocstyle
  - pytest
  - coverage
  - pyfakefs
  - pyflakes
  - jedi
  - autopep8
  - yapf
  - rope
  - twine

  - pip
  - pip:
    - afew
    - ipython-autoimport
    - -e ../Documents/Libraries/Python/filefinder
    - -e ../Documents/Libraries/Python/Tol_colors
    - -e ../Documents/Libraries/Python/xarray-histogram
    - -e ../Documents/Libraries/Python/MyPack
