name: default
dependencies:
  - python=3.10

  - jupyterlab
  - ipython
  - jupyter_console

  # basic science stack
  - numpy
  - scipy
  - pandas
  - numba

  # visualization stack
  - matplotlib
  - cartopy
  - cmocean

  # Xarray
  - xarray
  - netCDF4
  - pydap
  # Alternative to read netcdf files. Instead of using the python bindings
  # to the netCDF C-library, use the hdf5 python library (h5py).
  # Can be faster than netcdf4.
  - h5netcdf
  # speedup some operations
  - bottleneck
  # decode times
  - cftime
  # for plotting cftime.datetime objects
  - nc-time-axis

  # Dask
  - dask
  # visualize graphs
  - python-graphviz

  # Linting
  - ruff
  # jedi allows autocompletion
  - jedi
  - pytest
  - coverage

  # LSP
  - python-lsp-server

  - pip
  - pip:
    - afew
    - ipython-autoimport
    - tol-colors
