name: default
# channels:
#   - conda-forge
#   - defaults
dependencies:
  - python=3.10.*

  - jupyterlab
  - ipython
  - jupyter_console

  - numpy=1.23.*
  - scipy=1.9.*
  - pandas=1.5.*
  - numba

  - matplotlib=3.6.*
  - cartopy
  - cmocean
  - tabulate

  - xarray=2022.10.*
  - dask=2022.10.*
  - netCDF4=1.5.*
  - h5netcdf=1.0.*
  - h5py=3.7.*
  - bottleneck=1.3.*
  - cftime=1.6.*
  - pydap
  - nc-time-axis

  - boost-histogram=1.3.*
  - dask-histogram=2022.9.*
  - xhistogram=0.3.*

  - graphviz
  - python-graphviz

  - motuclient=1.8.*
  - shapely

  - sphinx
  - sphinx_rtd_theme

  - bibtexparser

  - python-lsp-server
  - flake8
  - pycodestyle
  - pydocstyle
  - pytest
  - coverage
  - pyfakefs
  - pyflakes
  - jedi
  - autopep8
  - yapf
  - rope
  - twine

  - pip
  - pip:
    - afew
    - -e ../Documents/Libraries/Python/filefinder
    - -e ../Documents/Libraries/Python/Tol_colors
    - -e ../Documents/Libraries/Python/xarray-histogram
    - -e ../Documents/Libraries/Python/MyPack
