#!/bin/bash

echo "Tag new messages"
afew -tn

echo "Move thrashed messages"
afew -mn --notmuch-args="--no-hooks"

echo "Mark older thrashed messages for deletion"
notmuch tag +deleted -thrashed tag:thrashed and date:..2_month

echo "Delete messages"
notmuch search --format=text0 --output=files tag:deleted | xargs -0 --no-run-if-empty rm

# Archive older messages
IFS=$'\n'
files=($(notmuch search --output=files \
    not tag:inbox and not tag:flagged and date:..3months and not path:'archives/**'))
unset IFS
dry=1
year="$(date +%Y)"

echo "Archive older message [dry=${dry}] (${#files[@]} files)"

for f in "${files[@]}"; do
    f_rel="$(realpath --relative-to "$MAILDIR" "$f")"
    target_base="$(basename "$f")"
    target_dir="$MAILDIR/archives/$year/$(dirname "$f_rel")"
    target_file="$target_dir/$target_base"

    if [ ! -d "$target_dir" ]; then
        echo "Creating target directory $target_dir"
        mkdir -p "$target_dir"
    fi

    if [ -f "$target_file" ]; then
        echo "File already exist $target_file"
    else
        if [ "$dry" == 0 ]; then
            mv "$f" "$target_file"
        else
            echo "mv $f $target_file"
        fi
    fi

done

# Update database (files may have been moved or deleted)
notmuch new --no-hooks --quiet
