#!/bin/bash


count="$(notmuch count tag:new)"
if [[ $count -gt 0 ]]; then
    echo "Tag new messages ($count)"
    afew -tn
fi

search="^posteo|locean|ens|orange/Trash|TRASH/.*"
count="$(notmuch count --exclude=false tag:trashed and not path:"/$search/")"
if [[ $count -gt 0 ]]; then
    echo "Move trashed messages ($count)"
    afew -mn --notmuch-args="--no-hooks"
fi

search="tag:trashed and date:..2months"
count="$(notmuch count "$search")"
if [[ count -gt 0 ]]; then
    echo "Mark older trashed messages for deletion ($count)"
    notmuch tag +deleted -trashed "$search"
fi

search="tag:deleted and date:..8days"
count="$(notmuch count "$search")"
if [[ count -gt 0 ]]; then
    echo "Delete messages ($count)"
    notmuch search --exclude=false --format=text0 --output=files "$search" | xargs -0 --no-run-if-empty rm
fi

# Archive older messages
IFS=$'\n'
files=($(notmuch search --exclude=false --output=files \
    not tag:inbox and not tag:flagged and date:..3months and not path:'archives/**'))
unset IFS
dry=0
year="$(date +%Y)"

count="${#files[@]}"
if [[ $count -gt 0 ]]; then
    echo "Archive older message [dry=${dry}] ($count)"

    for f in "${files[@]}"; do
        f_rel="$(realpath --relative-to "$MAILDIR" "$f")"
        target_base="$(basename "$f")"
        target_dir="$MAILDIR/archives/$year/$(dirname "$f_rel")"
        target_file="$target_dir/$target_base"

        if [ ! -d "$target_dir" ]; then
            echo "Creating target directory $target_dir"
            mkdir -p "$target_dir"
        fi

        if [ -f "$target_file" ]; then
            echo "File already exist $target_file"
        else
            if [ "$dry" == 0 ]; then
                mv "$f" "$target_file"
            else
                echo "mv $f $target_file"
            fi
        fi

    done
fi

# Update database (files may have been moved or deleted)
notmuch new --no-hooks --quiet
